/** @format */

export const GET_SEARCH_ARTICLE_ATTEMP = 'GET_SEARCH_ARTICLE_ATTEMP';
export const GET_SEARCH_ARTICLE_SUCCESS = 'GET_SEARCH_ARTICLE_SUCCESS';
export const GET_SEARCH_ARTICLE_FAILURE = 'GET_SEARCH_ARTICLE_FAILURE';

export const UPDATE_RECENT_SEARCH_ARTICLE_ATTEMP =
	'UPDATE_RECENT_SEARCH_ARTICLE_ATTEMP';
export const UPDATE_RECENT_SEARCH_ARTICLE_SUCCESS =
	'UPDATE_RECENT_SEARCH_ARTICLE_SUCCESS';
export const UPDATE_RECENT_SEARCH_ARTICLE_FAILURE =
	'UPDATE_RECENT_SEARCH_ARTICLE_FAILURE';
