/** @format */

export const ATTEMPT_LOGIN = 'ATTEMPT_LOGIN';
export const ATTEMPT_LOGIN_SUCCESS = 'ATTEMPT_LOGIN_SUCCESS';
export const ATTEMPT_LOGIN_FAILURE = 'ATTEMPT_LOGIN_FAILURE';

export const ATTEMPT_SIGN_UP = 'ATTEMPT_SIGN_UP';
export const ATTEMPT_SIGN_UP_SUCCESS = 'ATTEMPT_SIGN_UP_SUCCESS';
export const ATTEMPT_SIGN_UP_FAILURE = 'ATTEMPT_SIGN_UP_FAILURE';
