/** @format */

const ROUTES = {
	HOME: 'HOME',
	PRODUCT_DESCRIPTION: 'PRODUCT_DESCRIPTION',
	LOGIN: 'LOGIN',
	SIGN_UP: 'SIGN_UP',
	SEARCH: 'SEARCH',
	SEARCH_RESULT: 'SEARCH_RESULT',
};

export {ROUTES};
